<?php
    $this->user()->enableAutologout();
    echo $this->doctype() 

?><html lang="<?php echo $this->locale()->getLanguage() ?>">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle()->append('Administration') ?>
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <?php echo $this->headLink() ?>
    </head>
    
    <body>
        	<?php if ($this->config()->get('production_site') && $_SERVER['HTTP_HOST'] != $this->config()->get('production_site')) : ?>
        		<div style="text-align: center; background-color: #f0ad4e; color: black; font-size: 12px">
    				<?php echo $this->escapeHtml($_SERVER['HTTP_HOST']) ?>
    			</div>
    		<?php endif ?>
    	
    	<nav class="navbar navbar-inverse navbar-top hidden-xs" role="navigation">
        	<div class="container">
            	<?php
            	   echo $this->navigation()
            	        ->setContainer($this->kofusNavigation('admin')->getContainer())
                        ->dropdownMenu()
                        ->setMaxDepth(1)
                        ->setRole($this->user()->getRole())
                        ->setAcl($this->user()->acl())
                        ->setUlClass('nav navbar-nav')
                        ->render();
            	?>
            <?php if ($this->user()->getAccount()) : ?>
            	<ul class="nav navbar-nav navbar-right">
            		<li><a href="#">
            		     <?php echo $this->escapeHtml($this->user()->getAccount()->getName('display')) ?>
            		     (<span class="autologout-diff-h"><?php echo $this->user()->getAutologoutParam('diff_h') ?></span>)
            		     </a>
            		</li>
            		<li>
            		  <a href="<?php echo $this->url('logout') ?>"><span class="glyphicon glyphicon-off"></span></a>
            		</li>    					    	
        		</ul>
            <?php endif ?>
            
    		</div>
    		
    	</nav>
    	<div class="visible-xs">
        	<nav class="navbar navbar-inverse navbar-top visible-xs" role="navigation">
                <div class="container-fluid">
    	            <div class="navbar-header">
                        <?php if ($this->user()->isAllowed('System', 'logout')) : ?>
                            <a class="navbar-toggle" href="<?php echo $this->url('logout') ?>" title="Logout" style="color: white">
                                <i class="glyphicon glyphicon-off"></i>
                            </a>
                        <?php endif ?>
                        <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-mobile-main" aria-expanded="false">
                            <i style="color: white" class="glyphicon glyphicon-menu-hamburger"></i>
                        </button>
    	            </div>
    	            <div class="collapse navbar-collapse" id="nav-mobile-main">
    				<?php
    					echo $this->navigation()->dropdownMenu()
    							->setContainer($this->kofusNavigation('admin')->getContainer())
    							->setAcl($this->user()->acl())
    							->setRole($this->user()->getRole())
    							->setMaxDepth(0)
    							->setUlClass('nav navbar-nav')
    							->render()
    				?>
    	            </div>
    	        </div><!-- /.container-fluid -->			
    	    </nav>	
        </div>
        <div class="container">
	    	<?php echo $this->flashMessages() ?>
        	<?php echo $this->content ?>
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y') ?> <?php echo KOFUS_BRANDING ?>. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div>
        <?php echo $this->headScript() ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
