<div class="row">
    <div class="col-md-12">
        <h1><?php echo $this->translate('Newsgroups') ?></h1>
    </div>
    <div class="col-md-9">
        <?php if ($this->entities) : ?>
        	<table class="table table-hover">
        	   <thead>
        	       <tr>
        	       	   <th><?php echo $this->translate('Newsgroup') ?></th>
        	       	   <th><?php echo $this->translate('Subscribers') ?></th>
           	       </tr>
           	       
        	   </thead>
        	   <tbody data-link="row" class="rowlink">
        		<?php foreach ($this->entities as $entity) : ?>
        			<tr>
                        <td>
        				    <a href="<?php echo $this->url('kofus_mailer', array('controller' => 'newsgroup', 'action' => 'view', 'id' => $entity->getNodeId()), true) ?>">
        				    	<?php echo $this->escapeHtml($entity->getTitle()) ?>
        				    </a>
        			     </td>
        			     <td align="right">
        			         <?php echo $this->mailer()->countSubscriptions($entity) ?>
        			     </td>
        			</tr>			
        		<?php endforeach ?>
        		</tbody>
        	</table>
        <?php else : ?>
            <p><?php echo $this->translate('No entries.') ?></p>
        <?php endif ?>
    </div>
    <div class="col-md-3">
		  <div class="list-group">
		      <a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'add', 'id' => 'NEWSGROUP')) ?>" class="list-group-item">
		          <span class="glyphicon glyphicon-plus"></span>
		          <?php echo sprintf($this->translate('Add %s'), $this->translate('Newsgroup')) ?>
		      </a>
		  </div>
    </div>
</div>

    
