        <nav class="navbar navbar-default">
            <div class="container-fluid">
            <!-- 
            <ul class="nav navbar-nav">
                <li>
                    <a href=""><span class="glyphicon glyphicon-plus"></span> Hinzufügen</a>
                </li>
            </ul>
             -->
             <!-- 
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"><span class="glyphicon glyphicon-sort-by-alphabet"></span> </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">asdf</a></li>
                    </ul>
                </li>
            </ul>
             -->
            <form method="get" class="navbar-form navbar-right">
                <div class="form-group">
                    <input name="q" type="text" class="form-control" placeholder="<?php echo $this->translate('Search') ?>...">
                    <button type="submit" class="btn btn-default">
                    <span class="glyphicon glyphicon-search"></span></button>
                </div>
            </form>
            </div>
        </nav>
