<?php 
    $activeItems = $this->container->findAllBy('active', true);
    foreach ($activeItems as $activeItem) {
        if ($activeItem->getParent())
            $activeItems[] = $activeItem->getParent();
    }
    
?>

<ul class="<?php echo $this->navigation()->menu()->getUlClass() ?>">
	<?php 
	$prevDepth = 0;
	$iterator = new \RecursiveIteratorIterator(
			$this->container,
			RecursiveIteratorIterator::SELF_FIRST
	);
	?>
    <?php foreach ($iterator as $page) : ?>
        <?php
        	$depth = $iterator->getDepth();
        
            if ($page->getResource())
        	   if (! $this->user()->isAllowed($page->getResource(), $page->getPrivilege())) continue;
        	if ($page->get('enabled') === false) continue;
        
            $classes = explode(' ', $page->getClass()); 
            if ($page->hasPages() && $this->navigation()->menu()->getMaxDepth()) 
                $classes[] = 'dropdown';
            if (in_array($page, $activeItems))
                $classes[] = 'active';
            
            if ($page->get('image')) {
                $label = '<img src="'.$this->escapeHtmlAttr($page->get('image')).'" alt="'.$this->escapeHtmlAttr($page->getLabel()).'" title="'.$this->escapeHtmlAttr($page->getLabel()).'">';
            } elseif ($page->get('icon')) {
                $label = '<i class="'.$this->escapeHtmlAttr($page->get('icon')).'" title="'.$this->escapeHtmlAttr($page->getLabel()).'"></i> ';
            } else {
				$label = '';
			}
            $label .= $this->escapeHtml($this->translate($page->getLabel()));
            
            
        ?>
        <li <?php if ($page->get('id')) print 'id="'.$this->escapeHtmlAttr($page->get('id')) . '"' ?> class="<?php echo $this->escapeHtmlAttr(implode(' ', $classes)) ?>">
        
            <?php if ($page->hasPages() && $this->navigation()->menu()->getMaxDepth()) : ?>
                <a href="<?php echo $this->escapeHtmlAttr($page->getHref()) ?>" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown">
                    <?php echo $label ?> <span class="caret"></span>
                </a>
            <?php else : ?>
                <a href="<?php echo $this->escapeHtmlAttr($page->getHref()) ?>">
                    <?php echo $label ?>
                </a>
            <?php endif ?>
        <?php /* if ($page->hasPages() && $this->navigation()->menu()->getMaxDepth()) :  ?>
            <ul class="dropdown-menu" role="menu">
            <?php foreach ($page->getPages() as $child) : ?>
                <?php if ($child instanceof \Zend\Navigation\Page\Mvc) : ?>
                    <?php $params = $child->getParams() ?>
                    <?php $params['language'] = $this->locale()->getLanguage(); ?>
                    <?php $child->setParams($params) ?>
                <?php endif ?>
                <?php
                    $classes = explode(' ', $child->getClass()); 
                    if ($child->getLabel() == '-----' && $child->getUri() == '#')
                        $classes[] = 'divider';
                    if ($page->isActive())
                        $classes[] = 'active';
                ?>
                <li class="<?php echo $this->escapeHtmlAttr(implode(' ', $classes)) ?>">
                    <?php if (! ($child->getLabel() == '-----' && $child->getUri() == '#')) : ?>
                        <a href="<?php echo $this->escapeHtmlAttr($child->getHref()) ?>">
                            <?php echo $this->escapeHtml($this->translate($child->getLabel())) ?> 
                        </a>
                    <?php endif ?>
                </li>
            <?php endforeach ?>
            </ul>
        <?php endif */ ?>
        
        </li>
    <?php endforeach ?>
</ul>

