		<ul class="<?php echo $this->navigation()->menu()->getUlClass() ?>" role="menu">
            <?php foreach ($this->page->getPages() as $child) : ?>
                <?php
                    $classes = explode(' ', $child->getClass()); 
                    if ($child->getLabel() == '-----' && $child->getUri() == '#')
                        $classes[] = 'divider';
                    if ($this->page->isActive())
                        $classes[] = 'active';
                ?>
                <li class="<?php echo $this->escapeHtmlAttr(implode(' ', $classes)) ?>">
                    <?php if (! ($child->getLabel() == '-----' && $child->getUri() == '#')) : ?>
                        <a href="<?php echo $this->escapeHtmlAttr($child->getHref()) ?>">
                            <?php echo $this->escapeHtml($child->getLabel()) ?> 
                        </a>
                    <?php endif ?>
                    <?php $maxDepth = $this->navigation()->menu()->getMaxDepth() ?>
	                <?php if (($maxDepth === null || $this->depth < $maxDepth) && $child->hasPages()) : ?>  
	        			<?php echo $this->partial('cms/bootstrap/sub.phtml', array('page' => $child, 'depth' => $this->depth + 1)) ?>
	        		<?php endif ?>
                </li>
            <?php endforeach ?>
          </ul>
