<div class="row">
	<div class="col-md-9">
		<h1><?php echo $this->translate('Batch') ?></h1>
		<?php if ($this->batches) : ?>
			<table class="table">
				<tr>
					<th>ID</th>
					<th>Class</th>
					<th>Status</th>
					<th>Dauer</th>
				</tr>
				<?php foreach ($this->batches as $batch) : ?>
					<?php $id = $batch->getMetaParam('id') ?>
					<tr>
						<td>
							<?php echo $this->escapeHtml($id) ?>
						</td>
						<td>
							<?php echo $this->escapeHtml($batch->getMetaParam('classname')) ?>
						</td>
						<td>
							<?php echo $this->escapeHtml($batch->getMetaParam('current_index')) ?>
							/
							<?php echo $this->escapeHtml($batch->getMetaParam('last_index')) ?>
						</td>
						<td>
							<?php echo $this->escapeHtml($batch->getMetaParam('elapsed')) ?>
						</td>
						<td>
							<a href="<?php echo $this->url('kofus_system', array('controller' => 'batch', 'action' => 'run', 'id' => $id), array(), true) ?>">Run</a>
							<a href="<?php echo $this->url('kofus_system', array('controller' => 'batch', 'action' => 'run', 'id' => $id), array('query' => array('loop' => 1)), true) ?>">Loop</a>
							<a href="<?php echo $this->url('kofus_system', array('controller' => 'batch', 'action' => 'reset', 'id' => $id), array(), true) ?>">Reset</a>
						</td>
					</tr>
				<?php endforeach ?>
			</table>
		<?php endif ?>
	</div>
	<div class="col-md-3">
		  <div class="list-group">
		      <a href="<?php echo $this->url('kofus_system', array('controller' => 'batch', 'action' => 'reload'), true) ?>" class="list-group-item">
		          <span class="glyphicon glyphicon-update"></span>
		          <?php echo $this->translate('Load from config') ?>
		      </a>
		  </div>
    </div>	
</div>
