<div class="row">
	<div class="col-md-9">
		<h1>Stapelverarbeitung läuft...</h1>
		<h2><?php echo $this->batch->getMetaParam('classname') ?></h2>
		<p>
			<?php echo $this->escapeHtml($this->batch->getMetaParam('current_index')) ?>
			/
			<?php echo $this->escapeHtml($this->batch->getMetaParam('last_index')) ?>
		</p>
		<p>
			<?php 
				$proTask = $this->batch->getMetaParam('elapsed') / $this->batch->getMetaParam('current_index');
				print '<p>' . $proTask . 's / item</p>';
				$todo = $this->batch->getMetaParam('last_index') - $this->batch->getMetaParam('current_index');
				print '<p>noch ' . (number_format($todo * $proTask / 60)) . ' min</p>';
			?>
		</p>
	</div>
</div>

<script type="text/javascript">
	self.location.reload();
</script>