<h1>Abonnements</h1>
<div class="row">
	<div class="col-md-9">
        <?php if ($this->paginator->count()) : ?>
        	<table class="table table-hover">
        	   <thead>
        	       <tr>
        	           <th>Datum</th>
            	       <th>Name</th>
            	       <th>E-Mail</th>
            	       <th>Newsgroups</th>
          	       </tr>
        	   </thead>
        	   <tbody data-link="row" class="rowlink">
        		<?php foreach ($this->paginator as $entity) : ?>
        			<tr>
        			     <td>
        			         <?php echo $this->dateFormat($entity->getTimestampCreated(), \IntlDateFormatter::SHORT, \IntlDateFormatter::NONE) ?>
        			     </td>
        			     <td>
        			         <?php echo $this->escapeHtml($entity->getLastName()) ?>,
        			         <?php echo $this->escapeHtml($entity->getFirstName()) ?>
        			     </td>
        			     <td>
        			         <?php echo $this->escapeHtml($entity->getEmailAddress()) ?>
        			     </td>
        			     <td>
        			         <?php $newsgroups = array() ?>
        			         <?php foreach ($entity->getNewsgroups() as $newsgroup) : ?>
        			             <?php  $newsgroups[] = $newsgroup->getTitle() ?>
        			         <?php endforeach ?>
        			         <?php echo $this->escapeHtml(implode(', ', $newsgroups)) ?>
        			     </td>
        			     
        			 </tr>			
        		<?php endforeach ?>
        		</tbody>
        	</table>
        <?php else : ?>
            <p>Keine Einträge.</p>
        <?php endif ?>
        
    </div>
    <div class="col-md-3">
		  <div class="list-group">
		      <a href="/data/item/add/msub" class="list-group-item">
		          <span class="glyphicon glyphicon-plus"></span>
		          Hinzufügen
		      </a>
		  </div>
    </div>
</div>