    <?php $form = $this->form ?>
	<?php foreach ($form as $fieldset) : ?>
        <?php 
            if (! $fieldset instanceof \Zend\Form\FieldsetInterface) 
                continue;
            $fieldsetLocale = substr($fieldset->getName(), 0, 5);
            if (! in_array($fieldsetLocale, $this->config()->get('locales.available')))
                $fieldsetLocale = 'de_DE';
            if ($this->locale_filter != $fieldsetLocale)
                continue;  
        ?> 
        <div class="panel panel-default">
            <?php if ($fieldset->getLabel()) : ?>
                <div class="panel-heading">
                    <?php echo $this->escapeHtml($this->translate($fieldset->getLabel())) ?>
                    <?php if ($fieldsetLocale != 'de_DE') echo '[' . substr($fieldsetLocale, 0, 2) . ']' ?>
                </div>
            <?php endif ?>
		     <div class="panel-body">
				<fieldset class="form-horizontal">
					<?php 
						$sFormContent = '';
						$bHasColumnSizes = false;
						$sFormLayout = 'horizontal';
						foreach($fieldset as $oElement){
							$aOptions = $oElement->getOptions();
							if (!$bHasColumnSizes && !empty($aOptions['column-size'])) {
								$bHasColumnSizes = true;
							}
							//Define layout option to form elements if not already defined
							if($sFormLayout && empty($aOptions['twb-layout'])){
								$aOptions['twb-layout'] = $sFormLayout;
								$oElement->setOptions($aOptions);
							}
							
							if ($oElement instanceof \Zend\Form\FieldsetInterface) {
                                $sFormContent .= $this->formCollection($oElement);
                            } else {
                                $sFormContent .= $this->formRow($oElement);
                            }
						}
						if ($bHasColumnSizes && $sFormLayout !== 'horizontal') {
							$sFormContent = sprintf('<div class="row">%s</div>', $sFormContent);
						}
						echo $sFormContent;
					?>
					</fieldset>
                </div>						
			</div>
		<?php endforeach ?>
		<?php foreach ($form->getElements() as $element) : ?>
            <?php echo $this->formElement($element) ?>
        <?php endforeach ?>
