<h1><?php echo $this->translate('Permission denied') ?>.</h1>

<?php if ($this->displayExceptions) : ?>
    <p><?php echo sprintf($this->translate('%s is not allowed to access %s::%s'), '<b>' . $this->routeParams['matched_role'] . '</b>', '<b>' . $this->routeParams['matched_resource'] . '</b>', '<b>' . $this->routeParams['matched_action'] . '</b>') ?>.</p>
<?php else : ?>
    <p><?php echo $this->translate('You are not authorised to access this resource. You might want to check this:') ?></p>
    <ul>
        <li><?php echo $this->translate('Is the URL of this page correct?') ?></li>
        <li><?php echo $this->translate('Have you logged in with an appropriate account for this resource?') ?></li>
    </ul>
<?php endif ?>

