<?php echo $this->nodeNavigation('TV', 'list') ?>
<div class="row">
	<div class="col-md-9">
		<?php if ($this->paginator->getTotalItemCount()) : ?>
			<table class="table _table-hover">
               <tbody class="_rowlink" data-link="_row">
					<?php foreach ($this->paginator as $entity) : ?>
						<tr>
							<td>
								<a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $entity->getNodeId())) ?>">
									<?php echo $this->escapeHtml($entity->getTitle()) ?>
								</a>
							</td>
							<td>
								<?php $tags = $this->nodes()->getRepository('T')->findBy(array('vocabulary' => $entity)) ?>
								<?php if (count($tags)) : ?>
									<ul>
        								<?php foreach ($tags as $tag) : ?>
        									<li>
        										<a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $tag->getNodeId())) ?>">
        											<?php echo $this->escapeHtml($tag->getTitle())  ?>
        											<?php if ($tag->getParent()) : ?>
        												(<?php echo $this->escapeHtml($tag->getParent()->getTitle()) ?>)
        											<?php endif ?>
        										</a>
        									</li>
        								<?php endforeach ?>
    								</ul>
								<?php endif ?>							
							</td>
						</tr>
					<?php endforeach ?>
				</tbody>
			</table>
			
		<?php else : ?>
			<p>Keine Einträge.</p>
		<?php endif ?>
	</div>
</div>