<?php echo $this->nodeNavigation('TV', 'list') ?>
		<?php if ($this->paginator->getTotalItemCount()) : ?>
			<table class="table table-hover">
				<thead>
					<tr>
						<th>Vokabular</th>
						<th style="text-align: right">Tag-Einträge</th>
					</tr>
				</thead>
                <tbody class="rowlink" data-link="row">
					<?php foreach ($this->paginator as $entity) : ?>
						<tr>
							<td>
								<a href="<?php echo $this->url('kofus_system', array('controller' => 'tag-vocabulary', 'action' => 'view', 'id' => $entity->getNodeId())) ?>">
									<?php echo $this->escapeHtml($entity->getTitle()) ?>
								</a>
							</td>
							<td style="text-align: right">
								<?php $tags = $this->nodes()->getRepository('T')->findBy(array('vocabulary' => $entity)) ?>
								<?php print count($tags)?>						
							</td>
						</tr>
					<?php endforeach ?>
				</tbody>
			</table>
			<?php echo $this->paginationControl() ?>
		<?php else : ?>
			<p>Keine Einträge.</p>
		<?php endif ?>
