<div class="row">
    <div class="col-md-12">
        <?php echo $this->nodeNavigation('U', 'list') ?>
        <?php if ($this->paginator->count()) : ?>

            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>
                            <?php echo $this->paginationColumnSort('id', 'ID') ?>
                        </th>
                        <th>
                            <?php echo $this->paginationColumnSort('role', 'Role') ?>
                        </th>   
                        <th>
                            Name
                        </th>
                        <th>
                        	<?php echo $this->paginationColumnSort('date_login', 'Last login') ?>
                        </th>
                        <th>
                        	<?php echo $this->paginationColumnSort('date_created', 'Member since') ?>
                        </th>
                    </tr>
                </thead>
                <tbody data-link="row" class="rowlink">
                    <?php foreach ($this->paginator as $entity) : ?>
                        <?php if ($entity->getStatus() == 0) $css = 'warning' ?>
                        <?php if ($entity->getStatus() < 0) $css = 'danger' ?>
                        <?php if ($entity->getStatus() > 0) $css = 'success' ?>
                        <tr class="<?php if ($css) echo $css ?>">
                            <td>
                            	<a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $entity->getNodeId())) ?>">
                                	<?php echo $this->escapeHtml($entity->getNodeId()) ?>
                                </a>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($this->translate($entity->getRole())) ?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($entity->getName()) ?>
                            </td>
                            <td>
                            	<?php echo $this->dateFormat($entity->getTimestampLogin(), \IntlDateFormatter::SHORT) ?>
                            </td>
                            <td>
                            	<?php echo $this->dateFormat($entity->getTimestampCreated(), \IntlDateFormatter::SHORT) ?>
                            </td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
                <?php ?>
            </table>
            <?php echo $this->paginationControl($this->paginator) ?>
        <?php else : ?>
            <p><?php echo $this->escapeHtml($this->translate('No entries.')) ?></p>
        <?php endif ?>
    </div>
</div>