<div class="row">
    <div class="col-md-12">
        <h1><?php echo $this->escapeHtml($this->entity->getName()) ?></h1>
    </div>
    <div class="col-md-9">
        <h2>Zugangsdaten</h2>
        <?php if ($this->auths) : ?>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th><?php echo $this->translate('Type') ?></th>
                        <th><?php echo $this->translate('Identity') ?></th>
                    </tr>
                </thead>
                <tbody class="rowlink" data-link="row">
                    <?php foreach ($this->auths as $auth) : ?>
                        <tr>
                            <td>
                                <a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $auth->getNodeId())) ?>">
                                    <?php echo $this->escapeHtml($auth->getType(true)) ?>
                                </a>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($auth->getIdentity()) ?>
                            </td>
                            
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        <?php else : ?>
            <p><?php echo $this->translate('No entries.') ?></p>
        <?php endif ?>
    </div>
    <div class="col-md-3">
        <div class="list-group">
            <a href="<?php echo $this->urlBack() ?>" class="list-group-item">
                <i class="fa"></i>
                <?php echo $this->translate('Close') ?>
            </a>
            <a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $this->entity->getNodeId()), array(), true) ?>" class="list-group-item">
                <i class="glyphicon glyphicon-pencil"></i>
                <?php echo $this->translate('Edit') ?>
            </a>
            <a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'add', 'id' => 'AUTH'), array('query' => array('account' => $this->entity->getNodeId()))) ?>" class="list-group-item">
                <i class="glyphicon glyphicon-plus"></i>
                <?php echo $this->translate('Authentication') ?>
            </a>
        </div>
    </div>
</div>

