 <?php $relations = $this->config()->get('relations.enabled') ?>

        <div class="list-group">
            <a href="<?php echo $this->archive()->uriStack()->first() ?>" class="list-group-item">
                <span class="glyphicon"></span>
                    <?php echo $this->translate('Close') ?>
            </a>
            <a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $this->entity->getNodeId()), true) ?>" class="list-group-item">
                <span class="glyphicon glyphicon-pencil"></span>
                    <?php echo $this->translate('Edit') ?>
            </a>
            <?php foreach ($relations as $_relation) : ?>
                <?php $relation = explode('_', $_relation) ?>
                <?php if ($relation[0] == $this->entity->getNodeType()) : ?>
                    <?php $config = $this->config()->get('nodes.available.' . $relation[1]) ?>
                    <a href="<?php echo $this->url('kofus_system', array('controller' => 'relation', 'action' => 'add', 'id' => $this->entity->getNodeId()), true)  ?>?add=<?php echo $relation[1] ?>" class="list-group-item">
                        <span class="glyphicon glyphicon-plus"></span>
                            <?php echo $this->translate($config['label']) ?>
                    </a>                    
                <?php endif ?>
            <?php endforeach ?>
        </div>
