<div class="row">
	<div class="col-md-9">
		<h1>Cron</h1>
		<?php if ($this->tasks) : ?>
			<table class="table">
				<tr>
					<th>ID</th>
					<th>Cron</th>
					<th>Status</th>
					<th>min</th>
					<th>h</th>
					<th>day</th>
					<th>month</th>
					<th>week</th>
				</tr>
				<?php foreach ($this->tasks as $id => $task) : ?>
				    <?php $record = $this->scheduler->getRecord($id) ?>
					<tr>
						<td>
                            <?php echo $this->escapeHtml($id) ?>						  
						</td>
						<td>
						    <?php echo $this->escapeHtml($task[5]) ?>
						</td>
						<td>
                            <?php if ($record) echo $record['status'] ?>						  
						</td>
						<td>
                            <?php echo $this->escapeHtml($task[0]) ?>						  
						</td>
						<td>
                            <?php echo $this->escapeHtml($task[1]) ?>						  
						</td>
						<td>
                            <?php echo $this->escapeHtml($task[2]) ?>						  
						</td>
						</tr>
				<?php endforeach ?>
			</table>
	    <?php else: ?>
	       <p><?php echo $this->translate('No entries.')?></p>
		<?php endif ?>
	</div>
	
</div>
