<div class="row">
    <div class="col-md-12">
        <h1>
            <?php echo $this->escapeHtml($this->translate('HTTP')) ?>:
            <?php echo $this->escapeHtml($this->namespace) ?>
        </h1>
    </div>
    <div class="col-md-9">
        <?php if ($this->paginator->count()) : ?>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th><?php echo $this->translate('Timestamp') ?>
                        <th><?php echo $this->translate('Method') ?></th>
                        <th><?php echo $this->translate('URI') ?>
                    </tr>
                </thead>
                <tbody data-link="row" class="rowlink">
                    <?php foreach ($this->paginator as $result) : ?>
                        <?php
                            if ($result->getStatusCode() < 300) {
                                $css = 'success';
                            } elseif ($result->getStatusCode() < 400) {
                                $css = 'warning';
                            } else {
                                $css = 'danger';
                            }
                        ?>
                        <tr class="<?php echo $css ?>">
                            <td>
                                <a href="<?php echo $this->url('kofus_archive', array('controller' => 'http', 'action' => 'view', 'namespace' => $this->namespace, 'id' => $result->getId()), true) ?>">
                                    <?php echo $this->dateFormat($result->getTimestamp(), \IntlDateFormatter::SHORT, \IntlDateFormatter::SHORT) ?>
                                </a>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($result->getMethod()) ?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($result->getUri()) ?>
                            </td>
                            <td>
                            
                            </td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
            <?php echo $this->paginationControl($this->paginator) ?>
        <?php else : ?>
            <p><?php echo $this->escapeHtml($this->translate('No entries.')) ?></p>
        <?php endif ?>
    </div>
    <div class="col-md-3">
        <div class="list-group">
	      <a href="<?php echo $this->urlBack() ?>" class="list-group-item">
	          <?php echo $this->escapeHtml($this->translate('Close')) ?>
	      </a>
        </div>
    </div>
    
</div>