<?php echo $this->nodeNavigation('TAG', 'list') ?>
<div class="row">
	<div class="col-md-9">
		<?php if ($this->paginator->getTotalItemCount()) : ?>
			<table class="table table-hover">
               <tbody class="rowlink" data-link="row">
					<?php foreach ($this->paginator as $entity) : ?>
						<tr>
							<td>
								<a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $entity->getNodeId())) ?>">
									<?php echo $this->escapeHtml($entity->getTitle()) ?>
								</a>
							</td>
							<td>
								<?php echo $this->escapeHtml($entity->getVocabulary()->getTitle()) ?>
							</td>
						</tr>
					<?php endforeach ?>
				</tbody>
			</table>
			
		<?php else : ?>
			<p>Keine Einträge.</p>
		<?php endif ?>
	</div>
</div>