<?php echo $this->nodeNavigation('T', 'list') ?>

		<?php if ($this->paginator->getTotalItemCount()) : ?>
			<table class="table table-hover">
				<thead>
					<tr>
						<th>Tag</th>
						<th>Übergeordnetes Tag</th>
						<th>Vokabular</th>
					</tr>
				</thead>
               <tbody class="rowlink" data-link="row">
					<?php foreach ($this->paginator as $entity) : ?>
						<tr>
							<td>
								<a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $entity->getNodeId())) ?>">
									<?php echo $this->escapeHtml($entity->getTitle()) ?>
								</a>
							</td>
							<td>
								<?php if ($entity->getParent()) : ?>
									<span style="color: gray"><?php echo $this->escapeHtml($entity->getParent()->getTitle()) ?></span>
								<?php endif ?>
							</td>
							<td>
								<?php if ($entity->getVocabulary()) : ?>
									<?php echo $this->escapeHtml($entity->getVocabulary()->getTitle()) ?>
								<?php endif ?>
							</td>
						</tr>
					<?php endforeach ?>
				</tbody>
			</table>
			<?php echo $this->paginationControl() ?>
		<?php else : ?>
			<p>Keine Einträge.</p>
		<?php endif ?>
