<h1><?php echo $this->translate('Mail Templates') ?></h1>
<div class="row">
	<div class="col-md-9">
        <?php if ($this->entities) : ?>
        	<table class="table table-hover">
        	   <thead>
        	       <tr>
                        <th>ID</th>
                        <th><?php echo $this->translate('Administrative Title') ?></th>
                        <th><?php echo $this->translate('Subject') ?></th>
          	       </tr>
        	   </thead>
        	   <tbody data-link="row" class="rowlink">
        		<?php foreach ($this->entities as $entity) : ?>
        			<tr>
                        <td>
                            <?php echo $this->escapeHtml($entity->getNodeId()) ?>
                        </td>
                        <td>
                            <?php echo $this->escapeHtml($entity->getTitle()) ?>
                        </td>
        			     <td>
        				    <a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $entity->getNodeId()), true) ?>">
        				        <?php echo $this->escapeHtml($entity->getSubject()) ?>
        				    </a>
        			     </td>
        				</tr>			
        		<?php endforeach ?>
        		</tbody>
        	</table>
        <?php else : ?>
            <p><?php echo $this->translate('No entries.') ?></p>
        <?php endif ?>
        
    </div>
    <div class="col-md-3">
		  <div class="list-group">
		      <a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'add', 'id' => 'MTMPL'), true) ?>" class="list-group-item">
		          <span class="glyphicon glyphicon-plus"></span>
		          <?php echo $this->translate('Add') ?>
		      </a>
		  </div>
    </div>
</div>