<h1>Übersetzungen</h1>

<?php if ($this->missingTranslations) : ?>
	<?php if ($this->config()->get('deepl.enabled', false)) : ?>
    	<div class="dropdown pull-right">
    		<button class="btn _btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    	        Offene Übersetzungen (<?php echo $this->activeLocale ?>)
        	    <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <li>
                	<a href="<?php echo $this->url('kofus_system', array('controller' => 'translations', 'action' => 'deepl', 'id' => $this->activeLocale)) ?>">
    					Automatisch übersetzen (DeepL)
                	</a>
                </li>
                <li class="divider"></li>
                <li>
                	<a href="<?php echo $this->url('kofus_system', array('controller' => 'translations', 'action' => 'delete-orphans', 'id' => $this->activeLocale)) ?>">
    					<span class="glyphicon glyphicon-trash"></span>
    					Löschen
                	</a>
                </li>
            </ul>
        </div>
	<?php endif ?>
	
	<ul class="nav nav-tabs" role="tablist">
		<?php foreach ($this->missingTranslations as $locale => $translations) : ?>
			<li <?php if ($this->activeLocale == $locale) echo 'class="active"' ?>>
				<a href="<?php echo $this->url('kofus_system', array('controller' => 'translations', 'action' => 'list', 'id' => $locale)) ?>" role="tab">
					<?php echo $this->locale()->getDisplayLanguage($locale) ?>
					(<?php echo $this->locale()->getRegion($locale) ?>)&nbsp;
					<span class="badge"><?php echo count($translations) ?></span>
				</a>
			</li>
		<?php endforeach ?>
	</ul>
	<div class="tab-content">
		<div class="tab-pane active" role="tabpanel">
			<table class="table table-hover">
				<thead>
					<tr>
						<th>System-Sprache</th>
						<th>
        					<?php echo $this->locale()->getDisplayLanguage($this->activeLocale) ?>
        					(<?php echo $this->locale()->getRegion($this->activeLocale) ?>)
						</th>
						<th>Text-Domain</th>
						<th>Route</th>
						<th></th>
					</tr>
				</thead>
		        <tbody>
					<?php foreach ($this->missingTranslations[$this->activeLocale] as $translation) : ?>
						<tr <?php if (! $translation->getValue()) echo 'class="danger"'?>>
							<td>
								<?php echo $this->escapeHtml($translation->getMsgId()) ?>
							</td>
							<td>
								<?php echo $this->escapeHtml($translation->getValue()) ?>
							</td>
							<td>
								<?php echo $this->escapeHtml($translation->getTextDomain()) ?>
							</td>
							<td>
								<?php echo $this->escapeHtml($translation->getContextParam('route')) ?>
							</td>
							<td>
                            	<div class="dropdown pull-right">
                            		<button class="btn _btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                            	        <span class="glyphicon glyphicon-cog"></span>
                                	    <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                        <li>
                                        	<a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $translation->getNodeId())) ?>">
                            					Bearbeiten
                                        	</a>
                                        </li>
                                        <li>
                                        	<a href="<?php echo $this->url('kofus_system', array('controller' => 'translations', 'action' => 'deepl', 'id' => $translation->getNodeId())) ?>">
                            					Automatisch übersetzen (DeepL)
                                        	</a>
                                        </li>
                                        <li class="divider"></li>
                                        <li>
                                        	<a href="<?php echo $this->url('kofus_system', array('controller' => 'translations', 'action' => 'delete', 'id' => $translation->getNodeId())) ?>">
                            					<span class="glyphicon glyphicon-trash"></span>
                            					Löschen
                                        	</a>
                                        </li>
                                    </ul>
                                </div>
							</td>
						</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		</div>
	</div>


<?php endif ?>