<?php $form = $this->form ?>
<div class="row">
	<div class="col-md-9">
		<h1><?php echo $this->translate('Search index') ?></h1>
		<?php echo $this->form()->openTag($form) ?>
		<table class="table">
			<?php foreach ($this->nodeTypes as $nodeType => $delta) : ?>
				<tr>
					<td>
						<?php echo $this->formElement($form->get($nodeType)) ?>
					</td>
					<td>
						<?php echo $this->escapeHtml($nodeType) ?>
					</td>
					<td>
						<?php echo $this->escapeHtml($this->translate($delta['config']['label'])) ?>
					</td>
					<?php foreach ($this->config()->get('locales.enabled') as $locale) : ?>
						<td>
							<?php echo $delta[$locale] ?>
						</td>
					<?php endforeach ?>
				</tr>
			<?php endforeach ?>
		</table>

		<?php echo $this->formElement($form->get('delete')) ?>
		<?php echo $this->formElement($form->get('index')) ?>
		<?php echo $this->form()->closeTag() ?>
	</div>
</div>