<div class="row">
	<div class="col-md-8">
		<?php 
            echo $this->partial('kofus/system/page/template/relation_column.phtml', array(
                'entity' => $this->entity,
                'columnTitle' => 'Column 8',
                'columnId' => '8'
    		)) 
		?>
	</div>
	<div class="col-md-4">
		<?php 
            echo $this->partial('kofus/system/page/template/relation_column.phtml', array(
                'entity' => $this->entity,
                'columnTitle' => 'Column 4',
                'columnId' => '4'
    		)) 
		?>
	</div>
</div>

