					<div class="panel panel-default">
						<div class="panel-heading">
            				<div class="dropdown pull-right">
            					<button class="btn" type="button" data-toggle="dropdown" style="background: transparent; margin-top: -8px">
            						<span class="glyphicon glyphicon-cog"></span>
            					</button>
            					<ul class="dropdown-menu">
            						<li>
            							<a href="<?php echo $this->url('kofus_system', array('controller' => 'relation', 'action' => 'edit', 'id' => $this->relation->getId()), array('query' => array('edit' => $this->relation->getNode()->getNodeType()))) ?>">
            								<span class="glyphicon glyphicon-pencil"></span>
            								Edit
            							</a>
            						</li>
            						<li>
            							<a href="<?php echo $this->url('kofus_system', array('controller' => 'relation', 'action' => 'delete', 'id' => $this->relation->getId())) ?>">
            								<span class="glyphicon glyphicon-remove"></span>
            								Unlink Page Segment
            							</a>
            						</li>
            						<li>
            							<a href="<?php echo $this->url('kofus_system', array('controller' => 'relation', 'action' => 'delete', 'id' => $this->relation->getId()), array('query' => array('delete' => $this->relation->getNode()->getNodeType()))) ?>">
            								<span class="glyphicon glyphicon-remove"></span>
            								Delete Page Segment
            							</a>
            						</li>
            						
            					</ul>
            				</div>
							<h4 class="panel-title">
								<?php echo $this->escapeHtml($this->relation->getNode()->getTitle() . ' (' . $this->relation->getNode()->getNodeId() . ')') ?>
							</h4>
						</div>
						<div class="panel-body">
							<?php echo $this->relation->getNode()->getContent() ?>
						</div>
					</div>
