<div class="row">
    <div class="col-md-12">
        <h1><?php echo sprintf($this->translate('Add %s') , $this->translate($this->nodeTypeConfig['label'])) ?> </h1>
    </div>
	<div class="col-md-9">
       <?php echo $this->form()->openTag($this->form) ?>
	   <?php echo $this->partial($this->formTemplate, array('form' => $this->form, 'locale_filter' => $this->config()->get('locales.default'))) ?>
	   <?php echo $this->form()->closeTag() ?>
	</div>
    <div class="col-md-3">
		  <div class="list-group">
            <a href="<?php echo $this->urlBack() ?>" class="list-group-item">
		  		<?php echo $this->translate('Close') ?>
		      </a>
		  </div>
    </div>
</div>