<div class="row">
    <div class="col-md-12">
        <h1><?php echo $this->escapeHtml(sprintf($this->translate('Delete %s?'), $this->translate($this->nodeTypeConfig['label']))) ?></h1>
        <p><?php echo $this->escapeHtml(sprintf($this->translate('Do you really want to delete %s now?'), $this->entity)) ?></p>
        <a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'delete', 'id' => $this->entity->getNodeId()), array('query' => array('confirm' => $this->token)), true) ?>" class="btn btn-danger">
            <?php echo $this->translate('Delete') ?>
        </a>
        <a href="<?php echo $this->urlBack() ?>" class="btn btn-default">
            <?php echo $this->translate('Close') ?>
        </a>
    </div>
</div>