<div class="row">
    <div class="col-md-12">
        <?php echo $this->nodeNavigation('UR', 'list') ?>
        <?php if ($this->entities) : ?>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>
                            ID
                        </th>
                        <th>
                            Rolle
                        </th>
                        <th>
                        	Erbt von
                        </th>
                    </tr>
                </thead>
                <tbody data-link="row" class="rowlink">
                    <?php foreach ($this->entities as $entity) : ?>
                        <tr>
                            <td>
                            	<a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $entity->getNodeId())) ?>">
                                	<?php echo $this->escapeHtml($entity->getNodeId()) ?>
                                </a>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($entity->getName()) ?>
                            </td>
                            <td>
                            	<?php if ($entity->getParent()) : ?>
                            		<?php echo $this->escapeHtml($entity->getParent()) ?>
                            	<?php endif ?>
                            </td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
                <?php ?>
            </table>
        <?php else : ?>
            <p><?php echo $this->escapeHtml($this->translate('No entries.')) ?></p>
        <?php endif ?>
    </div>
</div>