<div class="row">
    <div class="col-md-12">
        <h1><?php echo $this->escapeHtml($this->translate('Mails')) ?></h1>
    </div>
    <div class="col-md-9">
        <?php if ($this->paginator->getTotalItemCount()) : ?>
            <?php echo $this->paginationControl($this->paginator) ?>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th><?php echo $this->translate('Subject') ?>
                        <th><?php echo $this->translate('To') ?></th>
                        <th><?php echo $this->translate('Sent') ?>
                        
                    </tr>
                </thead>
                <tbody data-link="row" class="rowlink">
                    <?php foreach ($this->paginator as $mail) : ?>
                        <tr>
                            <td>
                                <?php echo $this->escapeHtml($mail->getObject()->getSubject())  ?>
                            </td>
                            <td>
                                <?php foreach ($mail->getObject()->getTo() as $address) : ?>
                                    <?php echo $this->escapeHtml($address->getEmail()) ?>
                                <?php endforeach ?>
                            </td>
                            <td>
                                <a href="<?php echo $this->url('kofus_archive', array('controller' => 'mail', 'action' => 'view', 'id' => $mail->getId()), true) ?>">
                                    <?php echo $this->dateFormat($mail->getTimestamp(), \IntlDateFormatter::SHORT, \IntlDateFormatter::SHORT) ?>
                                </a>
                            </td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
            <?php echo $this->paginationControl($this->paginator) ?>
            
        <?php else : ?>
            <p><?php echo $this->escapeHtml($this->translate('No entries.')) ?></p>
        <?php endif ?>
    </div>
    <div class="col-md-3">
        <div class="list-group">
	      <a href="<?php echo $this->urlBack() ?>" class="list-group-item">
	          <?php echo $this->escapeHtml($this->translate('Close')) ?>
	      </a>
        </div>
    </div>
    
</div>