<div class="row">
    <div class="col-md-12">
        <h1><?php echo sprintf($this->translate('%s for %s') , $this->translate($this->nodeTypeConfig['label']), $this->relatedNode) ?> </h1>
    </div>
	<div class="col-md-9">
	
	<ul class="nav nav-tabs" role="tablist">
        <?php $isFirst = true ?>
        <?php foreach ($this->actions as $action) : ?>
            <?php if ('create' == $action) : ?>
                <li class="<?php if ($isFirst) echo 'active' ?>">
                    <a href="#create-and-link" role="tab" data-toggle="tab">
                        <?php echo sprintf($this->translate('Create and link %s'), $this->translate($this->nodeTypeConfig['label'])) ?>
                    </a>
                </li>
            <?php elseif ('link' == $action) : ?>        	   
                <li class="<?php if ($isFirst) echo 'active' ?>">
                    <a href="#link" role="tab" data-toggle="tab">
                        <?php echo sprintf($this->translate('Link %s'), $this->translate($this->nodeTypeConfig['label'])) ?>
                    </a>
                </li>
            <?php endif ?>
            <?php $isFirst = false ?>
        <?php endforeach ?>
	</ul>
	
	<div class="tab-content">
        <?php $isFirst = true ?>
        <?php foreach ($this->actions as $action) : ?>
            <?php if ('create' == $action) : ?>
                <div role="tabpanel" class="tab-pane <?php if ($isFirst) echo 'active' ?>" id="create-and-link">
                    <?php echo $this->form()->openTag($this->formCreate) ?>
                    <?php echo $this->partial($this->formTemplate, array('form' => $this->formCreate)) ?>
                    <?php echo $this->form()->closeTag() ?>
                </div>
            <?php elseif ('link' == $action) : ?>
                <div role="tabpanel" class="tab-pane <?php if ($isFirst) echo 'active' ?>" id="link">
                    <?php echo $this->form()->openTag($this->formLink) ?>
                    <?php echo $this->partial($this->formTemplate, array('form' => $this->formLink)) ?>
                    <?php echo $this->form()->closeTag() ?>
                </div>
            <?php endif ?>
            <?php $isFirst = false ?>
        <?php endforeach ?>
	</div>
	
	
	</div>
    <div class="col-md-3">
		  <div class="list-group">
		      <a href="<?php echo $this->urlback() ?>" class="list-group-item">
		          <?php echo $this->translate('Close') ?>
		      </a>
		  </div>
    </div>
    
    
</div>