<div class="row">
    <div class="col-md-12">
        <h1><?php echo $this->translate('Delete?') ?></h1>
        <p><?php echo $this->escapeHtml($this->translate('Do you really want to delete the relation?')) ?></p>
        <a href="<?php echo $this->url('kofus_system', array('controller' => 'relation', 'action' => 'delete', 'id' => $this->relation->getId()), array('query' => array('confirm' => $this->token, 'delete' => $this->nodeType))) ?>" class="btn btn-danger">
            <?php echo $this->translate('Delete') ?>
        </a>
        <a href="<?php echo $this->urlBack() ?>" class="btn btn-default">
            <?php echo $this->translate('Close') ?>
        </a>
    </div>
</div>