<?php foreach ($this->delta as $r) : ?>
    <?php $node = $r->getNode() ?>
    <div class="panel-group">
        <div class="panel <?php echo ($node->isEnabled()) ? 'panel-default' : 'panel-danger' ?>">
            <div class="panel-heading">
            	<?php echo $this->partial('kofus/system/relations/dropdown.phtml', array('r' => $r, 'type' => $type)) ?>
                <h4 class="panel-title">
                    <a class="collapsed" data-toggle="collapse" href="#collapse-<?php echo $node->getNodeId() ?>">
                        <?php echo $node ?>
                    </a>
                </h4>
            </div>
            <div id="collapse-<?php echo $node->getNodeId() ?>" class="panel-collapse collapse">
                <div class="panel-body">
                    <?php if (method_exists($node, 'getContent')) : ?>
                        <?php echo $node->getContent() ?>
                    <?php endif ?>
                </div>
            </div>
        </div>
    </div>


<?php endforeach ?>


