    <div class="dropdown pull-right">
            <a href="#" class="dropdown-toggle" type="button" data-toggle="dropdown">
                <span class="glyphicon glyphicon-cog"></span>
            </a>
            <ul class="dropdown-menu">
                <li>
                    <a href="<?php echo $this->url('kofus_system', array('controller' => 'relation', 'action' => 'edit', 'id' => $r->getId())) ?>?edit=<?php echo $type ?>">
                        <span class="glyphicon glyphicon-pencil"></span>
                        <?php echo $this->translate('Edit') ?>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->url('kofus_system', array('controller' => 'relation', 'action' => 'delete', 'id' => $r->getId())) ?>?delete=<?php echo $type ?>">
                        <span class="glyphicon glyphicon-remove"></span>
                        <?php echo $this->translate('Delete') ?>
                    </a>
                </li>
            </ul>
	</div>