<div class="row">
	<?php foreach ($this->delta as $r) : ?>
        <?php $node = $r->getNode() ?>
        <div class="col-md-3">
            <div class="panel <?php echo ($node->isEnabled()) ? 'panel-default' : 'panel-danger' ?>">
                <div class="panel-heading">
                	<?php echo $this->partial('kofus/system/relations/dropdown.phtml', array('r' => $r, 'type' => $type)) ?>
                    <h4 class="panel-title">
                        <a data-toggle="collapse" href="#collapse-<?php echo $node->getNodeId() ?>">
                            <?php echo $node->getNodeId() ?>
                        </a>
                    </h4>
                </div>
                <div id="collapse-<?php echo $node->getNodeId() ?>" class="panel-collapse in ">
                    <div class="panel-body">
                        <img src="<?php echo $this->media()->getImageLink($node, 'thumb') ?>" class="img-responsive">
                        <br>
                        <?php echo $this->escapeHtml($node->getTitle()) ?>
                    </div>
                </div>
    	    </div>
    	</div>
	<?php endforeach ?>
</div>

