<div class="row">
    <div class="col-md-12">
        <h1>
            <?php echo $this->escapeHtml($this->translate('SOAP')) ?>:
            <?php echo $this->escapeHtml($this->namespace) ?>
        </h1>
    </div>
    <div class="col-md-9">
        <?php if ($this->paginator->count()) : ?>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th><?php echo $this->translate('Timestamp') ?>
                        <th><?php echo $this->translate('Request') ?></th>
                        <th><?php echo $this->translate('Response') ?>
                    </tr>
                </thead>
                <tbody data-link="row" class="rowlink">
                    <?php foreach ($this->paginator as $result) : ?>
                        <tr>
                            <td>
                                <a href="<?php echo $this->url('kofus_archive', array('controller' => 'soap', 'action' => 'view', 'namespace' => $this->namespace, 'id' => $result->getId()), true) ?>">
                                    <?php echo $this->dateFormat($result->getTimestamp(), \IntlDateFormatter::SHORT, \IntlDateFormatter::SHORT) ?>
                                </a>
                            </td>
                            <td>
                                <?php
                                    $headers = explode("\n", $result->getRequestHeaders());
                                    echo $this->escapeHtml($headers[0]);  
                                 ?>
                            </td>
                            <td>
                                <?php
                                    $headers = explode("\n", $result->getResponseHeaders());
                                    echo $this->escapeHtml($headers[0]);  
                                 ?>
                            </td>
                            <td>
                            
                            </td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
            <?php echo $this->paginationControl($this->paginator) ?>
        <?php else : ?>
            <p><?php echo $this->escapeHtml($this->translate('No entries.')) ?></p>
        <?php endif ?>
    </div>
    <div class="col-md-3">
        <div class="list-group">
	      <a href="<?php echo $this->urlBack() ?>" class="list-group-item">
	          <?php echo $this->escapeHtml($this->translate('Close')) ?>
	      </a>
        </div>
    </div>
    
</div>