<div class="row">
    <div class="col-md-12">
        <h1>SOAP</h1>
    </div>
    <div class="col-md-9">
        <ul class="nav nav-tabs" role="tablist">
            <li class="active">
                <a href="#response" role="tab" data-toggle="tab">Response</a>
            </li>
            <li>
                <a href="#request" role="tab" data-toggle="tab">Request</a>
            </li>
        </ul>
        
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="response">
                <?php 
                    $body = $this->soap->getResponse();
                ?>
                <pre><?php echo $this->escapeHtml($body) ?></pre>
                <table class="table">
                    <?php foreach (explode("\n", $this->soap->getResponseHeaders()) as $header) : ?>
                        <tr>
                            <td>
                                <?php echo $this->escapeHtml($header) ?>
                            </td>
                        </tr>
                    <?php endforeach ?>
                </table>
                
            </div>
            <div role="tabpanel" class="tab-pane" id="request">
                <?php
                    $body = $this->soap->getRequest();
                ?>
                <pre><?php echo $this->escapeHtml($body) ?></pre>
                <table class="table">
                    <?php foreach (explode("\n", $this->soap->getRequestHeaders()) as $header) : ?>
                        <tr>
                            <td>
                                <?php echo $this->escapeHtml($header) ?>
                            </td>
                        </tr>
                    <?php endforeach ?>
                </table>
                
            </div>
        </div>
        
        
    </div>
    <div class="col-md-3">
        <div class="list-group">
	      <a href="<?php echo $this->urlBack() ?>" class="list-group-item">
	          <?php echo $this->escapeHtml($this->translate('Close')) ?>
	      </a>
        </div>
    </div>
</div>