
			<ul class="nav nav-tabs" role="tablist">
                <?php $isFirst = true ?>
                <?php foreach ($this->relations as $type => $data) : ?>
                    <?php if (! $data) continue ?>
                    <li class="<?php if ($isFirst) echo 'active' ?>">
                        <a href="<?php echo '#' . md5($type) ?>" role="tab" data-toggle="tab">
                            <?php echo $this->escapeHtml($this->translate($this->config()->get('nodes.available.'.$type.'.label_pl'))) ?>
                        </a>
                    </li>
                    <?php $isFirst = false ?>
                <?php endforeach ?>
            </ul>
            <div class="tab-content">
            	<br>
                <?php $isFirst = true ?>
                <?php foreach ($this->relations as $type => $delta) : ?>
                    <?php if (! $delta) continue ?>
                    <div role="tabpanel" class="tab-pane <?php if ($isFirst) echo 'active' ?>" id="<?php echo md5($type) ?>">
                        <?php 
                            switch ($type) {
                                case 'GIMG':
                                case 'PIMG':
                                case 'IMG':
                                    echo $this->partial('kofus/system/relations/IMG.phtml', array('delta' => $delta, 'type' => $type));
                                    break;
                                case 'PDF':
                                    echo $this->partial('kofus/system/relations/PDF.phtml', array('delta' => $delta, 'type' => $type));
                                    break;
                                case 'VF':
                                    echo $this->partial('kofus/system/relations/VF.phtml', array('delta' => $delta, 'type' => $type));
                                    break;
                                    
                                default:
                                    echo $this->partial('kofus/system/relations/default.phtml', array('delta' => $delta, 'type' => $type));
                                    
                            }
                        ?>
                    </div>
                    <?php $isFirst = false ?>
                <?php endforeach ?>
            </div>

