<div class="row">
    <div class="col-md-12">
        <h1><?php echo $this->translate('PDFs') ?></h1>
    </div>
    <div class="col-md-9">
        <?php if ($this->entities) : ?>
            <table class="table table-hover">
				<tbody data-link="row" class="rowlink">
                    <?php foreach ($this->entities as $entity) : ?>
                        <tr class="<?php if (!$entity->isEnabled()) echo 'danger'?>">
                            <td>
                                <a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'edit', 'id' => $entity->getNodeId()), true) ?>">
                                    <img src="<?php echo $this->media()->getImageLink($entity) ?>" class="img-responsive img-thumbnail" />
                                </a>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($entity->getTitle()) ?>
                            </td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
                <?php ?>
            </table>
        <?php else : ?>
            <p><?php echo $this->escapeHtml($this->translate('No entries.')) ?></p>
        <?php endif ?>
    </div>
    <div class="col-md-3">
        <div class="list-group">
    	      <a href="<?php echo $this->url('kofus_system', array('controller' => 'node', 'action' => 'add', 'id' => 'PDF'), array(), true) ?>" class="list-group-item">
    	          <span class="glyphicon glyphicon-plus"></span>
    	          <?php echo $this->escapeHtml($this->translate('Add')) ?>
    	      </a>
        </div>
    </div>
</div>