<div class="row">
    <div class="col-md-12">
        <h1>
            <?php echo $this->translate('Add PayPal Experience') ?>
        </h1>
    </div>
    <div class="col-md-9">
        <?php echo $this->form($this->form) ?>
    </div>
    <div class="col-md-3">
        <div class="list-group">
    	      <a class="list-group-item" href="<?php echo $this->archive()->uriStack()->first() ?>">
    	          <?php echo $this->escapeHtml($this->translate('Cancel')) ?>
    	      </a>
        </div>
    </div>
</div>