<div class="row">
    <div class="col-md-12">
        <h1><?php echo $this->escapeHtml($this->translate('PayPal Experiences')) ?></h1>
    </div>
    <div class="col-md-9">
        <?php if ($this->experiences) : ?>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                    </tr>
                </thead>
                <tbody data-link="row" class="rowlink">
                    <?php foreach ($this->experiences as $experience) : ?>
                        <tr>
                            <td>
                                <a href="<?php echo $this->url('kofus_webservice_ppplus', array('controller' => 'experience', 'action' => 'edit', 'id' => $experience->id)) ?>">
                                    <?php echo $this->escapeHtml($experience->id) ?>
                                </a>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($experience->name) ?>
                            </td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
                <?php ?>
            </table>
        <?php else : ?>
            <p><?php echo $this->escapeHtml($this->translate('No entries.')) ?></p>
        <?php endif ?>
    </div>
    <div class="col-md-3">
        <div class="list-group">
    	      <a href="<?php echo $this->url('kofus_webservice_ppplus', array('controller' => 'experience', 'action' => 'add'), array(), true) ?>" class="list-group-item">
    	          <span class="glyphicon glyphicon-plus"></span>
    	          <?php echo $this->escapeHtml($this->translate('Add')) ?>
    	      </a>
        </div>
    </div>
</div>