<div class="row">
    <div class="col-md-12">
        <h1><?php echo $this->escapeHtml($this->record['method']) ?> <?php echo $this->escapeHtml($this->record['uri']) ?></h1>
        
    </div>
    <div class="col-md-12">
   		<?php foreach ($this->records as $record) : ?>
   			<?php foreach (unserialize($record['backtrace']) as $backtrace) : ?>
   				<?php echo $this->escapeHtml(implode(' ', $backtrace)) ?><br>
   			<?php endforeach ?>
			<pre><?php echo $this->escapeHtml($record['sql']) ?></pre>
			<?php //echo $this->escapeHtml($record['params']) ?>
			<?php //echo $this->escapeHtml($record['types']) ?>
   		<?php endforeach ?>
    </div>
    <div class="col-md-3">
        <div class="list-group">
	      <a href="<?php echo $this->urlBack() ?>" class="list-group-item">
	          <?php echo $this->escapeHtml($this->translate('Close')) ?>
	      </a>
        </div>
    </div>
</div>